<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1experimental/pprofextended.proto

namespace Opentelemetry\Proto\Profiles\V1experimental;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents a mapping between Attribute Keys and Units.
 *
 * Generated from protobuf message <code>opentelemetry.proto.profiles.v1experimental.AttributeUnit</code>
 */
class AttributeUnit extends \Google\Protobuf\Internal\Message
{
    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 attribute_key = 1;</code>
     */
    protected $attribute_key = 0;
    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 unit = 2;</code>
     */
    protected $unit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $attribute_key
     *           Index into string table.
     *     @type int|string $unit
     *           Index into string table.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Experimental\Pprofextended::initOnce();
        parent::__construct($data);
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 attribute_key = 1;</code>
     * @return int|string
     */
    public function getAttributeKey()
    {
        return $this->attribute_key;
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 attribute_key = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAttributeKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->attribute_key = $var;

        return $this;
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 unit = 2;</code>
     * @return int|string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 unit = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkInt64($var);
        $this->unit = $var;

        return $this;
    }

}

