<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1experimental/pprofextended.proto

namespace Opentelemetry\Proto\Profiles\V1experimental;

use UnexpectedValueException;

/**
 * Indicates the semantics of the build_id field.
 *
 * Protobuf type <code>opentelemetry.proto.profiles.v1experimental.BuildIdKind</code>
 */
class BuildIdKind
{
    /**
     * Linker-generated build ID, stored in the ELF binary notes.
     *
     * Generated from protobuf enum <code>BUILD_ID_LINKER = 0;</code>
     */
    const BUILD_ID_LINKER = 0;
    /**
     * Build ID based on the content hash of the binary. Currently no particular
     * hashing approach is standardized, so a given producer needs to define it
     * themselves and thus unlike BUILD_ID_LINKER this kind of hash is producer-specific.
     * We may choose to provide a standardized stable hash recommendation later.
     *
     * Generated from protobuf enum <code>BUILD_ID_BINARY_HASH = 1;</code>
     */
    const BUILD_ID_BINARY_HASH = 1;

    private static $valueToName = [
        self::BUILD_ID_LINKER => 'BUILD_ID_LINKER',
        self::BUILD_ID_BINARY_HASH => 'BUILD_ID_BINARY_HASH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

