<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1experimental/pprofextended.proto

namespace Opentelemetry\Proto\Profiles\V1experimental;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes function and line table debug information.
 *
 * Generated from protobuf message <code>opentelemetry.proto.profiles.v1experimental.Location</code>
 */
class Location extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique nonzero id for the location.  A profile could use
     * instruction addresses or any integer sequence as ids. [deprecated]
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * The index of the corresponding profile.Mapping for this location.
     * It can be unset if the mapping is unknown or not applicable for
     * this profile type.
     *
     * Generated from protobuf field <code>uint64 mapping_index = 2;</code>
     */
    protected $mapping_index = 0;
    /**
     * The instruction address for this location, if available.  It
     * should be within [Mapping.memory_start...Mapping.memory_limit]
     * for the corresponding mapping. A non-leaf address may be in the
     * middle of a call instruction. It is up to display tools to find
     * the beginning of the instruction if necessary.
     *
     * Generated from protobuf field <code>uint64 address = 3;</code>
     */
    protected $address = 0;
    /**
     * Multiple line indicates this location has inlined functions,
     * where the last entry represents the caller into which the
     * preceding entries were inlined.
     * E.g., if memcpy() is inlined into printf:
     *    line[0].function_name == "memcpy"
     *    line[1].function_name == "printf"
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1experimental.Line line = 4;</code>
     */
    private $line;
    /**
     * Provides an indication that multiple symbols map to this location's
     * address, for example due to identical code folding by the linker. In that
     * case the line information above represents one of the multiple
     * symbols. This field must be recomputed when the symbolization state of the
     * profile changes.
     *
     * Generated from protobuf field <code>bool is_folded = 5;</code>
     */
    protected $is_folded = false;
    /**
     * Type of frame (e.g. kernel, native, python, hotspot, php). Index into string table.
     *
     * Generated from protobuf field <code>uint32 type_index = 6;</code>
     */
    protected $type_index = 0;
    /**
     * References to attributes in Profile.attribute_table. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 attributes = 7;</code>
     */
    private $attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Unique nonzero id for the location.  A profile could use
     *           instruction addresses or any integer sequence as ids. [deprecated]
     *     @type int|string $mapping_index
     *           The index of the corresponding profile.Mapping for this location.
     *           It can be unset if the mapping is unknown or not applicable for
     *           this profile type.
     *     @type int|string $address
     *           The instruction address for this location, if available.  It
     *           should be within [Mapping.memory_start...Mapping.memory_limit]
     *           for the corresponding mapping. A non-leaf address may be in the
     *           middle of a call instruction. It is up to display tools to find
     *           the beginning of the instruction if necessary.
     *     @type \Opentelemetry\Proto\Profiles\V1experimental\Line[]|\Google\Protobuf\Internal\RepeatedField $line
     *           Multiple line indicates this location has inlined functions,
     *           where the last entry represents the caller into which the
     *           preceding entries were inlined.
     *           E.g., if memcpy() is inlined into printf:
     *              line[0].function_name == "memcpy"
     *              line[1].function_name == "printf"
     *     @type bool $is_folded
     *           Provides an indication that multiple symbols map to this location's
     *           address, for example due to identical code folding by the linker. In that
     *           case the line information above represents one of the multiple
     *           symbols. This field must be recomputed when the symbolization state of the
     *           profile changes.
     *     @type int $type_index
     *           Type of frame (e.g. kernel, native, python, hotspot, php). Index into string table.
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $attributes
     *           References to attributes in Profile.attribute_table. [optional]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Experimental\Pprofextended::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique nonzero id for the location.  A profile could use
     * instruction addresses or any integer sequence as ids. [deprecated]
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Unique nonzero id for the location.  A profile could use
     * instruction addresses or any integer sequence as ids. [deprecated]
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * The index of the corresponding profile.Mapping for this location.
     * It can be unset if the mapping is unknown or not applicable for
     * this profile type.
     *
     * Generated from protobuf field <code>uint64 mapping_index = 2;</code>
     * @return int|string
     */
    public function getMappingIndex()
    {
        return $this->mapping_index;
    }

    /**
     * The index of the corresponding profile.Mapping for this location.
     * It can be unset if the mapping is unknown or not applicable for
     * this profile type.
     *
     * Generated from protobuf field <code>uint64 mapping_index = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMappingIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->mapping_index = $var;

        return $this;
    }

    /**
     * The instruction address for this location, if available.  It
     * should be within [Mapping.memory_start...Mapping.memory_limit]
     * for the corresponding mapping. A non-leaf address may be in the
     * middle of a call instruction. It is up to display tools to find
     * the beginning of the instruction if necessary.
     *
     * Generated from protobuf field <code>uint64 address = 3;</code>
     * @return int|string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * The instruction address for this location, if available.  It
     * should be within [Mapping.memory_start...Mapping.memory_limit]
     * for the corresponding mapping. A non-leaf address may be in the
     * middle of a call instruction. It is up to display tools to find
     * the beginning of the instruction if necessary.
     *
     * Generated from protobuf field <code>uint64 address = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkUint64($var);
        $this->address = $var;

        return $this;
    }

    /**
     * Multiple line indicates this location has inlined functions,
     * where the last entry represents the caller into which the
     * preceding entries were inlined.
     * E.g., if memcpy() is inlined into printf:
     *    line[0].function_name == "memcpy"
     *    line[1].function_name == "printf"
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1experimental.Line line = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * Multiple line indicates this location has inlined functions,
     * where the last entry represents the caller into which the
     * preceding entries were inlined.
     * E.g., if memcpy() is inlined into printf:
     *    line[0].function_name == "memcpy"
     *    line[1].function_name == "printf"
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1experimental.Line line = 4;</code>
     * @param \Opentelemetry\Proto\Profiles\V1experimental\Line[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLine($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opentelemetry\Proto\Profiles\V1experimental\Line::class);
        $this->line = $arr;

        return $this;
    }

    /**
     * Provides an indication that multiple symbols map to this location's
     * address, for example due to identical code folding by the linker. In that
     * case the line information above represents one of the multiple
     * symbols. This field must be recomputed when the symbolization state of the
     * profile changes.
     *
     * Generated from protobuf field <code>bool is_folded = 5;</code>
     * @return bool
     */
    public function getIsFolded()
    {
        return $this->is_folded;
    }

    /**
     * Provides an indication that multiple symbols map to this location's
     * address, for example due to identical code folding by the linker. In that
     * case the line information above represents one of the multiple
     * symbols. This field must be recomputed when the symbolization state of the
     * profile changes.
     *
     * Generated from protobuf field <code>bool is_folded = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFolded($var)
    {
        GPBUtil::checkBool($var);
        $this->is_folded = $var;

        return $this;
    }

    /**
     * Type of frame (e.g. kernel, native, python, hotspot, php). Index into string table.
     *
     * Generated from protobuf field <code>uint32 type_index = 6;</code>
     * @return int
     */
    public function getTypeIndex()
    {
        return $this->type_index;
    }

    /**
     * Type of frame (e.g. kernel, native, python, hotspot, php). Index into string table.
     *
     * Generated from protobuf field <code>uint32 type_index = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTypeIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->type_index = $var;

        return $this;
    }

    /**
     * References to attributes in Profile.attribute_table. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 attributes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * References to attributes in Profile.attribute_table. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 attributes = 7;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->attributes = $arr;

        return $this;
    }

}

