<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1experimental/profiles.proto

namespace Opentelemetry\Proto\Profiles\V1experimental;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A ProfileContainer represents a single profile. It wraps pprof profile with OpenTelemetry specific metadata.
 *
 * Generated from protobuf message <code>opentelemetry.proto.profiles.v1experimental.ProfileContainer</code>
 */
class ProfileContainer extends \Google\Protobuf\Internal\Message
{
    /**
     * A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
     * all zeroes is considered invalid.
     * This field is required.
     *
     * Generated from protobuf field <code>bytes profile_id = 1;</code>
     */
    protected $profile_id = '';
    /**
     * start_time_unix_nano is the start time of the profile.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * This field is semantically required and it is expected that end_time >= start_time.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     */
    protected $start_time_unix_nano = 0;
    /**
     * end_time_unix_nano is the end time of the profile.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * This field is semantically required and it is expected that end_time >= start_time.
     *
     * Generated from protobuf field <code>fixed64 end_time_unix_nano = 3;</code>
     */
    protected $end_time_unix_nano = 0;
    /**
     * attributes is a collection of key/value pairs. Note, global attributes
     * like server name can be set using the resource API. Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "/http/server_latency": 300
     *     "abc.com/myattribute": true
     *     "abc.com/score": 10.239
     * The OpenTelemetry API specification further restricts the allowed value types:
     * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute
     * Attribute keys MUST be unique (it is not allowed to have more than one
     * attribute with the same key).
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.KeyValue attributes = 4;</code>
     */
    private $attributes;
    /**
     * dropped_attributes_count is the number of attributes that were discarded. Attributes
     * can be discarded because their keys are too long or because there are too many
     * attributes. If this value is 0, then no attributes were dropped.
     *
     * Generated from protobuf field <code>uint32 dropped_attributes_count = 5;</code>
     */
    protected $dropped_attributes_count = 0;
    /**
     * Specifies format of the original payload. Common values are defined in semantic conventions. [required if original_payload is present]
     *
     * Generated from protobuf field <code>string original_payload_format = 6;</code>
     */
    protected $original_payload_format = '';
    /**
     * Original payload can be stored in this field. This can be useful for users who want to get the original payload.
     * Formats such as JFR are highly extensible and can contain more information than what is defined in this spec.
     * Inclusion of original payload should be configurable by the user. Default behavior should be to not include the original payload.
     * If the original payload is in pprof format, it SHOULD not be included in this field.
     * The field is optional, however if it is present `profile` MUST be present and contain the same profiling information.
     *
     * Generated from protobuf field <code>bytes original_payload = 7;</code>
     */
    protected $original_payload = '';
    /**
     * This is a reference to a pprof profile. Required, even when original_payload is present.
     *
     * Generated from protobuf field <code>.opentelemetry.proto.profiles.v1experimental.Profile profile = 8;</code>
     */
    protected $profile = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $profile_id
     *           A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
     *           all zeroes is considered invalid.
     *           This field is required.
     *     @type int|string $start_time_unix_nano
     *           start_time_unix_nano is the start time of the profile.
     *           Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     *           This field is semantically required and it is expected that end_time >= start_time.
     *     @type int|string $end_time_unix_nano
     *           end_time_unix_nano is the end time of the profile.
     *           Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     *           This field is semantically required and it is expected that end_time >= start_time.
     *     @type \Opentelemetry\Proto\Common\V1\KeyValue[]|\Google\Protobuf\Internal\RepeatedField $attributes
     *           attributes is a collection of key/value pairs. Note, global attributes
     *           like server name can be set using the resource API. Examples of attributes:
     *               "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *               "/http/server_latency": 300
     *               "abc.com/myattribute": true
     *               "abc.com/score": 10.239
     *           The OpenTelemetry API specification further restricts the allowed value types:
     *           https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute
     *           Attribute keys MUST be unique (it is not allowed to have more than one
     *           attribute with the same key).
     *     @type int $dropped_attributes_count
     *           dropped_attributes_count is the number of attributes that were discarded. Attributes
     *           can be discarded because their keys are too long or because there are too many
     *           attributes. If this value is 0, then no attributes were dropped.
     *     @type string $original_payload_format
     *           Specifies format of the original payload. Common values are defined in semantic conventions. [required if original_payload is present]
     *     @type string $original_payload
     *           Original payload can be stored in this field. This can be useful for users who want to get the original payload.
     *           Formats such as JFR are highly extensible and can contain more information than what is defined in this spec.
     *           Inclusion of original payload should be configurable by the user. Default behavior should be to not include the original payload.
     *           If the original payload is in pprof format, it SHOULD not be included in this field.
     *           The field is optional, however if it is present `profile` MUST be present and contain the same profiling information.
     *     @type \Opentelemetry\Proto\Profiles\V1experimental\Profile $profile
     *           This is a reference to a pprof profile. Required, even when original_payload is present.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Experimental\Profiles::initOnce();
        parent::__construct($data);
    }

    /**
     * A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
     * all zeroes is considered invalid.
     * This field is required.
     *
     * Generated from protobuf field <code>bytes profile_id = 1;</code>
     * @return string
     */
    public function getProfileId()
    {
        return $this->profile_id;
    }

    /**
     * A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
     * all zeroes is considered invalid.
     * This field is required.
     *
     * Generated from protobuf field <code>bytes profile_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileId($var)
    {
        GPBUtil::checkString($var, False);
        $this->profile_id = $var;

        return $this;
    }

    /**
     * start_time_unix_nano is the start time of the profile.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * This field is semantically required and it is expected that end_time >= start_time.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     * @return int|string
     */
    public function getStartTimeUnixNano()
    {
        return $this->start_time_unix_nano;
    }

    /**
     * start_time_unix_nano is the start time of the profile.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * This field is semantically required and it is expected that end_time >= start_time.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimeUnixNano($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_time_unix_nano = $var;

        return $this;
    }

    /**
     * end_time_unix_nano is the end time of the profile.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * This field is semantically required and it is expected that end_time >= start_time.
     *
     * Generated from protobuf field <code>fixed64 end_time_unix_nano = 3;</code>
     * @return int|string
     */
    public function getEndTimeUnixNano()
    {
        return $this->end_time_unix_nano;
    }

    /**
     * end_time_unix_nano is the end time of the profile.
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
     * This field is semantically required and it is expected that end_time >= start_time.
     *
     * Generated from protobuf field <code>fixed64 end_time_unix_nano = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTimeUnixNano($var)
    {
        GPBUtil::checkUint64($var);
        $this->end_time_unix_nano = $var;

        return $this;
    }

    /**
     * attributes is a collection of key/value pairs. Note, global attributes
     * like server name can be set using the resource API. Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "/http/server_latency": 300
     *     "abc.com/myattribute": true
     *     "abc.com/score": 10.239
     * The OpenTelemetry API specification further restricts the allowed value types:
     * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute
     * Attribute keys MUST be unique (it is not allowed to have more than one
     * attribute with the same key).
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.KeyValue attributes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * attributes is a collection of key/value pairs. Note, global attributes
     * like server name can be set using the resource API. Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "/http/server_latency": 300
     *     "abc.com/myattribute": true
     *     "abc.com/score": 10.239
     * The OpenTelemetry API specification further restricts the allowed value types:
     * https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute
     * Attribute keys MUST be unique (it is not allowed to have more than one
     * attribute with the same key).
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.KeyValue attributes = 4;</code>
     * @param \Opentelemetry\Proto\Common\V1\KeyValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opentelemetry\Proto\Common\V1\KeyValue::class);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * dropped_attributes_count is the number of attributes that were discarded. Attributes
     * can be discarded because their keys are too long or because there are too many
     * attributes. If this value is 0, then no attributes were dropped.
     *
     * Generated from protobuf field <code>uint32 dropped_attributes_count = 5;</code>
     * @return int
     */
    public function getDroppedAttributesCount()
    {
        return $this->dropped_attributes_count;
    }

    /**
     * dropped_attributes_count is the number of attributes that were discarded. Attributes
     * can be discarded because their keys are too long or because there are too many
     * attributes. If this value is 0, then no attributes were dropped.
     *
     * Generated from protobuf field <code>uint32 dropped_attributes_count = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDroppedAttributesCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->dropped_attributes_count = $var;

        return $this;
    }

    /**
     * Specifies format of the original payload. Common values are defined in semantic conventions. [required if original_payload is present]
     *
     * Generated from protobuf field <code>string original_payload_format = 6;</code>
     * @return string
     */
    public function getOriginalPayloadFormat()
    {
        return $this->original_payload_format;
    }

    /**
     * Specifies format of the original payload. Common values are defined in semantic conventions. [required if original_payload is present]
     *
     * Generated from protobuf field <code>string original_payload_format = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalPayloadFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->original_payload_format = $var;

        return $this;
    }

    /**
     * Original payload can be stored in this field. This can be useful for users who want to get the original payload.
     * Formats such as JFR are highly extensible and can contain more information than what is defined in this spec.
     * Inclusion of original payload should be configurable by the user. Default behavior should be to not include the original payload.
     * If the original payload is in pprof format, it SHOULD not be included in this field.
     * The field is optional, however if it is present `profile` MUST be present and contain the same profiling information.
     *
     * Generated from protobuf field <code>bytes original_payload = 7;</code>
     * @return string
     */
    public function getOriginalPayload()
    {
        return $this->original_payload;
    }

    /**
     * Original payload can be stored in this field. This can be useful for users who want to get the original payload.
     * Formats such as JFR are highly extensible and can contain more information than what is defined in this spec.
     * Inclusion of original payload should be configurable by the user. Default behavior should be to not include the original payload.
     * If the original payload is in pprof format, it SHOULD not be included in this field.
     * The field is optional, however if it is present `profile` MUST be present and contain the same profiling information.
     *
     * Generated from protobuf field <code>bytes original_payload = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->original_payload = $var;

        return $this;
    }

    /**
     * This is a reference to a pprof profile. Required, even when original_payload is present.
     *
     * Generated from protobuf field <code>.opentelemetry.proto.profiles.v1experimental.Profile profile = 8;</code>
     * @return \Opentelemetry\Proto\Profiles\V1experimental\Profile|null
     */
    public function getProfile()
    {
        return $this->profile;
    }

    public function hasProfile()
    {
        return isset($this->profile);
    }

    public function clearProfile()
    {
        unset($this->profile);
    }

    /**
     * This is a reference to a pprof profile. Required, even when original_payload is present.
     *
     * Generated from protobuf field <code>.opentelemetry.proto.profiles.v1experimental.Profile profile = 8;</code>
     * @param \Opentelemetry\Proto\Profiles\V1experimental\Profile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Opentelemetry\Proto\Profiles\V1experimental\Profile::class);
        $this->profile = $var;

        return $this;
    }

}

