<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1experimental/pprofextended.proto

namespace Opentelemetry\Proto\Profiles\V1experimental;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Each Sample records values encountered in some program
 * context. The program context is typically a stack trace, perhaps
 * augmented with auxiliary information like the thread-id, some
 * indicator of a higher level request being handled etc.
 *
 * Generated from protobuf message <code>opentelemetry.proto.profiles.v1experimental.Sample</code>
 */
class Sample extends \Google\Protobuf\Internal\Message
{
    /**
     * The indices recorded here correspond to locations in Profile.location.
     * The leaf is at location_index[0]. [deprecated, superseded by locations_start_index / locations_length]
     *
     * Generated from protobuf field <code>repeated uint64 location_index = 1;</code>
     */
    private $location_index;
    /**
     * locations_start_index along with locations_length refers to to a slice of locations in Profile.location.
     * Supersedes location_index.
     *
     * Generated from protobuf field <code>uint64 locations_start_index = 7;</code>
     */
    protected $locations_start_index = 0;
    /**
     * locations_length along with locations_start_index refers to a slice of locations in Profile.location.
     * Supersedes location_index.
     *
     * Generated from protobuf field <code>uint64 locations_length = 8;</code>
     */
    protected $locations_length = 0;
    /**
     * A 128bit id that uniquely identifies this stacktrace, globally. Index into string table. [optional]
     *
     * Generated from protobuf field <code>uint32 stacktrace_id_index = 9;</code>
     */
    protected $stacktrace_id_index = 0;
    /**
     * The type and unit of each value is defined by the corresponding
     * entry in Profile.sample_type. All samples must have the same
     * number of values, the same as the length of Profile.sample_type.
     * When aggregating multiple samples into a single sample, the
     * result has a list of values that is the element-wise sum of the
     * lists of the originals.
     *
     * Generated from protobuf field <code>repeated int64 value = 2;</code>
     */
    private $value;
    /**
     * label includes additional context for this sample. It can include
     * things like a thread id, allocation size, etc.
     * NOTE: While possible, having multiple values for the same label key is
     * strongly discouraged and should never be used. Most tools (e.g. pprof) do
     * not have good (or any) support for multi-value labels. And an even more
     * discouraged case is having a string label and a numeric label of the same
     * name on a sample.  Again, possible to express, but should not be used.
     * [deprecated, superseded by attributes]
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1experimental.Label label = 3;</code>
     */
    private $label;
    /**
     * References to attributes in Profile.attribute_table. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 attributes = 10;</code>
     */
    private $attributes;
    /**
     * Reference to link in Profile.link_table. [optional]
     *
     * Generated from protobuf field <code>uint64 link = 12;</code>
     */
    protected $link = 0;
    /**
     * Timestamps associated with Sample represented in nanoseconds. These timestamps are expected
     * to fall within the Profile's time range. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 timestamps_unix_nano = 13;</code>
     */
    private $timestamps_unix_nano;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $location_index
     *           The indices recorded here correspond to locations in Profile.location.
     *           The leaf is at location_index[0]. [deprecated, superseded by locations_start_index / locations_length]
     *     @type int|string $locations_start_index
     *           locations_start_index along with locations_length refers to to a slice of locations in Profile.location.
     *           Supersedes location_index.
     *     @type int|string $locations_length
     *           locations_length along with locations_start_index refers to a slice of locations in Profile.location.
     *           Supersedes location_index.
     *     @type int $stacktrace_id_index
     *           A 128bit id that uniquely identifies this stacktrace, globally. Index into string table. [optional]
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $value
     *           The type and unit of each value is defined by the corresponding
     *           entry in Profile.sample_type. All samples must have the same
     *           number of values, the same as the length of Profile.sample_type.
     *           When aggregating multiple samples into a single sample, the
     *           result has a list of values that is the element-wise sum of the
     *           lists of the originals.
     *     @type \Opentelemetry\Proto\Profiles\V1experimental\Label[]|\Google\Protobuf\Internal\RepeatedField $label
     *           label includes additional context for this sample. It can include
     *           things like a thread id, allocation size, etc.
     *           NOTE: While possible, having multiple values for the same label key is
     *           strongly discouraged and should never be used. Most tools (e.g. pprof) do
     *           not have good (or any) support for multi-value labels. And an even more
     *           discouraged case is having a string label and a numeric label of the same
     *           name on a sample.  Again, possible to express, but should not be used.
     *           [deprecated, superseded by attributes]
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $attributes
     *           References to attributes in Profile.attribute_table. [optional]
     *     @type int|string $link
     *           Reference to link in Profile.link_table. [optional]
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $timestamps_unix_nano
     *           Timestamps associated with Sample represented in nanoseconds. These timestamps are expected
     *           to fall within the Profile's time range. [optional]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Experimental\Pprofextended::initOnce();
        parent::__construct($data);
    }

    /**
     * The indices recorded here correspond to locations in Profile.location.
     * The leaf is at location_index[0]. [deprecated, superseded by locations_start_index / locations_length]
     *
     * Generated from protobuf field <code>repeated uint64 location_index = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocationIndex()
    {
        return $this->location_index;
    }

    /**
     * The indices recorded here correspond to locations in Profile.location.
     * The leaf is at location_index[0]. [deprecated, superseded by locations_start_index / locations_length]
     *
     * Generated from protobuf field <code>repeated uint64 location_index = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocationIndex($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->location_index = $arr;

        return $this;
    }

    /**
     * locations_start_index along with locations_length refers to to a slice of locations in Profile.location.
     * Supersedes location_index.
     *
     * Generated from protobuf field <code>uint64 locations_start_index = 7;</code>
     * @return int|string
     */
    public function getLocationsStartIndex()
    {
        return $this->locations_start_index;
    }

    /**
     * locations_start_index along with locations_length refers to to a slice of locations in Profile.location.
     * Supersedes location_index.
     *
     * Generated from protobuf field <code>uint64 locations_start_index = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLocationsStartIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->locations_start_index = $var;

        return $this;
    }

    /**
     * locations_length along with locations_start_index refers to a slice of locations in Profile.location.
     * Supersedes location_index.
     *
     * Generated from protobuf field <code>uint64 locations_length = 8;</code>
     * @return int|string
     */
    public function getLocationsLength()
    {
        return $this->locations_length;
    }

    /**
     * locations_length along with locations_start_index refers to a slice of locations in Profile.location.
     * Supersedes location_index.
     *
     * Generated from protobuf field <code>uint64 locations_length = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLocationsLength($var)
    {
        GPBUtil::checkUint64($var);
        $this->locations_length = $var;

        return $this;
    }

    /**
     * A 128bit id that uniquely identifies this stacktrace, globally. Index into string table. [optional]
     *
     * Generated from protobuf field <code>uint32 stacktrace_id_index = 9;</code>
     * @return int
     */
    public function getStacktraceIdIndex()
    {
        return $this->stacktrace_id_index;
    }

    /**
     * A 128bit id that uniquely identifies this stacktrace, globally. Index into string table. [optional]
     *
     * Generated from protobuf field <code>uint32 stacktrace_id_index = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setStacktraceIdIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->stacktrace_id_index = $var;

        return $this;
    }

    /**
     * The type and unit of each value is defined by the corresponding
     * entry in Profile.sample_type. All samples must have the same
     * number of values, the same as the length of Profile.sample_type.
     * When aggregating multiple samples into a single sample, the
     * result has a list of values that is the element-wise sum of the
     * lists of the originals.
     *
     * Generated from protobuf field <code>repeated int64 value = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The type and unit of each value is defined by the corresponding
     * entry in Profile.sample_type. All samples must have the same
     * number of values, the same as the length of Profile.sample_type.
     * When aggregating multiple samples into a single sample, the
     * result has a list of values that is the element-wise sum of the
     * lists of the originals.
     *
     * Generated from protobuf field <code>repeated int64 value = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->value = $arr;

        return $this;
    }

    /**
     * label includes additional context for this sample. It can include
     * things like a thread id, allocation size, etc.
     * NOTE: While possible, having multiple values for the same label key is
     * strongly discouraged and should never be used. Most tools (e.g. pprof) do
     * not have good (or any) support for multi-value labels. And an even more
     * discouraged case is having a string label and a numeric label of the same
     * name on a sample.  Again, possible to express, but should not be used.
     * [deprecated, superseded by attributes]
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1experimental.Label label = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * label includes additional context for this sample. It can include
     * things like a thread id, allocation size, etc.
     * NOTE: While possible, having multiple values for the same label key is
     * strongly discouraged and should never be used. Most tools (e.g. pprof) do
     * not have good (or any) support for multi-value labels. And an even more
     * discouraged case is having a string label and a numeric label of the same
     * name on a sample.  Again, possible to express, but should not be used.
     * [deprecated, superseded by attributes]
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1experimental.Label label = 3;</code>
     * @param \Opentelemetry\Proto\Profiles\V1experimental\Label[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLabel($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opentelemetry\Proto\Profiles\V1experimental\Label::class);
        $this->label = $arr;

        return $this;
    }

    /**
     * References to attributes in Profile.attribute_table. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 attributes = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * References to attributes in Profile.attribute_table. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 attributes = 10;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Reference to link in Profile.link_table. [optional]
     *
     * Generated from protobuf field <code>uint64 link = 12;</code>
     * @return int|string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Reference to link in Profile.link_table. [optional]
     *
     * Generated from protobuf field <code>uint64 link = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkUint64($var);
        $this->link = $var;

        return $this;
    }

    /**
     * Timestamps associated with Sample represented in nanoseconds. These timestamps are expected
     * to fall within the Profile's time range. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 timestamps_unix_nano = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimestampsUnixNano()
    {
        return $this->timestamps_unix_nano;
    }

    /**
     * Timestamps associated with Sample represented in nanoseconds. These timestamps are expected
     * to fall within the Profile's time range. [optional]
     *
     * Generated from protobuf field <code>repeated uint64 timestamps_unix_nano = 13;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimestampsUnixNano($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->timestamps_unix_nano = $arr;

        return $this;
    }

}

