<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1experimental/pprofextended.proto

namespace Opentelemetry\Proto\Profiles\V1experimental;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ValueType describes the type and units of a value, with an optional aggregation temporality.
 *
 * Generated from protobuf message <code>opentelemetry.proto.profiles.v1experimental.ValueType</code>
 */
class ValueType extends \Google\Protobuf\Internal\Message
{
    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 unit = 2;</code>
     */
    protected $unit = 0;
    /**
     * Generated from protobuf field <code>.opentelemetry.proto.profiles.v1experimental.AggregationTemporality aggregation_temporality = 3;</code>
     */
    protected $aggregation_temporality = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $type
     *           Index into string table.
     *     @type int|string $unit
     *           Index into string table.
     *     @type int $aggregation_temporality
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Experimental\Pprofextended::initOnce();
        parent::__construct($data);
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 type = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 unit = 2;</code>
     * @return int|string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Index into string table.
     *
     * Generated from protobuf field <code>int64 unit = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkInt64($var);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.opentelemetry.proto.profiles.v1experimental.AggregationTemporality aggregation_temporality = 3;</code>
     * @return int
     */
    public function getAggregationTemporality()
    {
        return $this->aggregation_temporality;
    }

    /**
     * Generated from protobuf field <code>.opentelemetry.proto.profiles.v1experimental.AggregationTemporality aggregation_temporality = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAggregationTemporality($var)
    {
        GPBUtil::checkEnum($var, \Opentelemetry\Proto\Profiles\V1experimental\AggregationTemporality::class);
        $this->aggregation_temporality = $var;

        return $this;
    }

}

