<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1experimental/profiles.proto

namespace GPBMetadata\Opentelemetry\Proto\Profiles\V1Experimental;

class Profiles
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Opentelemetry\Proto\Common\V1\Common::initOnce();
        \GPBMetadata\Opentelemetry\Proto\Resource\V1\Resource::initOnce();
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Experimental\Pprofextended::initOnce();
        $pool->internalAddGeneratedFile(
            '
·	
:opentelemetry/proto/profiles/v1experimental/profiles.proto+opentelemetry.proto.profiles.v1experimental.opentelemetry/proto/resource/v1/resource.proto?opentelemetry/proto/profiles/v1experimental/pprofextended.proto"h
ProfilesDataX
resource_profiles (2=.opentelemetry.proto.profiles.v1experimental.ResourceProfiles"¿
ResourceProfiles;
resource (2).opentelemetry.proto.resource.v1.ResourceR
scope_profiles (2:.opentelemetry.proto.profiles.v1experimental.ScopeProfiles

schema_url (	Jèé"¸
ScopeProfilesB
scope (23.opentelemetry.proto.common.v1.InstrumentationScopeO
profiles (2=.opentelemetry.proto.profiles.v1experimental.ProfileContainer

schema_url (	"Á
ProfileContainer

profile_id (
start_time_unix_nano (
end_time_unix_nano (;

attributes (2\'.opentelemetry.proto.common.v1.KeyValue 
dropped_attributes_count (
original_payload_format (	
original_payload (E
profile (24.opentelemetry.proto.profiles.v1experimental.ProfileB§
.io.opentelemetry.proto.profiles.v1experimentalBProfilesProtoPZ6go.opentelemetry.io/proto/otlp/profiles/v1experimentalª+OpenTelemetry.Proto.Profiles.V1Experimentalbproto3'
        , true);

        static::$is_initialized = true;
    }
}

